### ISSUE TITLE
[Enhancement]: TPE3 frame in ID3v2.3 should be used for narrator.

### ISSUE THREAD

**Issue by BrianAker** [sandreas/tone#70]
The TPE3 frame in ID3v2.3 is intended for “Conductor/Performer Refinement,” but it’s often used in audiobooks or spoken word media to denote the narrator. Many media players and library management tools recognize this frame and display it appropriately.
	•	Example: TPE3 = “Narrated by John Doe”

When trying to do the following with a file which uses ID3v2.3 the following fails silently:
tone tag --meta-narrator 

The fix is just to map it to TPE3 for ID3v2.3.

Additionally, whenever tone fails to update a file a return value should be given so that a script can handle the failure. POSIX systems and windows allow to you use the return values between 1-254 for whatever you want ( BSD has sysexits.h, but it is not a hard rule at all ).  Being able to programmatically errors would be very useful, at the moment you have to update and then open the file again to see if the changes you requested succeeded. I am happy to write this up in more detail if you want it as its own feature request.

**Comment by sandreas** [comment]
@BrianAker 
Thank you for taking the time. Accoring to [MP3Tag Mapping](https://docs.mp3tag.de/mapping/#conductor) `TPE3` is used for `Conductor`, not `Narrator`.

`Narrator` has no mapping for id3v2. Since I'm following these pretty accurately with minor exceptions, I'd recommend to use `--meta-conductor="Authors Name"` to fix this for your use case. If you don't want to specify the narrator twice, you can also use `--meta-conductor="Authors Name" --meta-equate="conductor,narrator"` to overcome the problem. 

However, since there is a possibility to use an extended field in id3v2 (`TXXX:NARRATOR`), I would implement this in addition to the `conductor` mapping to have at least any narrator mapping for id3v2. 

Targeted for next release.

**Comment by sandreas** [comment]
Waiting for response here:
https://github.com/Zeugma440/atldotnet/issues/289

**Comment by BrianAker** [comment]
Thanks!

**Comment by sandreas** [comment]
Should be fixed in `0.2.0`.
